### ISSUE TITLE
Job Maps, Blog posting, GIN website

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/DDH_HomelessServices#2]
When this thing comes together, time to publicize it. The usual: the GIN website, maybe a blog posting or a tweet, Job Maps.

**Comment by gregallensworth** [comment]
A starting place:   http://www.greeninfo.org/work/project/1181

Also, 3 screenshots added to `J:\GINFO\GIN_Job_Maps\JobMaps2018`

**Comment by danrademacher** [comment]
On the website: http://www.greeninfo.org/work/project/eastbay-homeless

And queued up for next Maplines
