### ISSUE TITLE
Data cleanup: Asterisks in AgencyName

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/DDH_HomelessServices#30]
![image](https://user-images.githubusercontent.com/3117633/37535607-7dc29cec-2905-11e8-95c2-f7d3d877badf.png)

Some service providers have asterisks in their name. The visible result of this in the application is confusing, as there is no legend for why a provider should have this by their name.

* Remove the asterisks from provider names
* OR, standardize why these exist, and add a legend to the app?

I do have availability, so could go in and do the data cleanup myself if you prefer.

**Comment by danrademacher** [comment]
Added new "verified field" in AirTable for admin use and removed all the asterisks. No change needed in end user site
