### ISSUE TITLE
Data cleanup: Records missing AgencyName + Address

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/DDH_HomelessServices#31]
Discovered in issue #29 there is a data issue: some records are missing their AgencyName and/or their Address. As a result, these are skipped in the UI because they break the UI... and because they would not be useful even if they could be displayed.

The following records have been identified so far, but all records should be examined.

![image](https://user-images.githubusercontent.com/3117633/37535827-2234e1cc-2906-11e8-9bed-00cf958f7c85.png)
![image](https://user-images.githubusercontent.com/3117633/37535853-354e5a86-2906-11e8-912d-096aafa332c6.png)

**Comment by danrademacher** [comment]
Updated and fixed records with missing info
