### ISSUE TITLE
Add new URL and Facebook links in agency detail panel

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/DDH_HomelessServices#32]
New fields in AirTable:
`url`
`facebook`

Both are URLs, currently without `http...` attached, though we can do that if needed.

Just add them here after Description, before Services:

![image](https://user-images.githubusercontent.com/1423200/37573950-2cc52b6c-2ada-11e8-927f-b5f59e770ba7.png)

Simple underlined links:
[Website]()
[Facebook Page]()

**Comment by gregallensworth** [comment]
Links added. Of course, this only appears if the appropriate link(s) is/are defined.

The `http://` is prepended automagically *if it is absent* so as to support both "partial" URLs and also properly-formatted ones.

![image](https://user-images.githubusercontent.com/3117633/37603544-1b44be6c-2b4c-11e8-9f4e-6a4fcd6d5067.png)
