### ISSUE TITLE
Data & Display: no times given

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/DDH_HomelessServices#33]
![image](https://user-images.githubusercontent.com/3117633/37602377-769f9bf4-2b49-11e8-99f9-f9bd9c5a4c65.png)

This entry lacks start or end times. As a result, the only left-justified bit is blank and the whole entry is indented. Would it do well to add some other heading, e.g. All Day or Call For Hours or something?

**Comment by danrademacher** [comment]
I'll check with the data editors and see if the missing times mean "all day" or if they simply neglected to include the times

**Comment by danrademacher** [comment]
There are 17 records without start time - and some are missing days and would therefore never appear. 

https://airtable.com/shruGypdm6iTiL0YM/tblCsWJj89Fo3qzXF

Reported to the data editors at the homeless shelter.

**Comment by danrademacher** [comment]
Confirmed these are all-day items, so let's have it say "All Day" if no time is present
