### ISSUE TITLE
Location details now has underline on the X

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/DDH_HomelessServices#34]
![image](https://user-images.githubusercontent.com/3117633/37603260-6d467d32-2b4b-11e8-8251-ab03a3460227.png)

The X to close the details panel, now has an underline on it. On all other projects, I have been very specifically asked to remove these, but this one has one.

I was about to remove it, but see here *index.scss line 356* an entry for it: `text-decoration: underline!important;`

Is this intentional that the X have an underline, unlike those in all other applications to date? Or shall I remove it?

**Comment by danrademacher** [comment]
Looking at Git history [here](https://github.com/GreenInfo-Network/DDH_HomelessServices/commit/f8b873e5212e9d910ec04ff5f05fb545ba0dfa35), it looks like the X underline was a side-effect of forcing underlines on the other links in the panel. 

The X should not have an underline.

**Comment by gregallensworth** [comment]
Great! Will do.
