### ISSUE TITLE
Selected item highlight

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/DDH_HomelessServices#35]
In use, it's hard for folks to tell which one of these orange circles are wrong:
![image](https://user-images.githubusercontent.com/1423200/37748211-3b7fc046-2d40-11e8-9b7d-97a77b150e05.png)

Here's an SVG in Django-button green for selected item:
https://github.com/GreenInfo-Network/DDH_HomelessServices/blob/master/images/location-selected.svg

So it would show green on map and in panel:
![image](https://user-images.githubusercontent.com/1423200/37748801-67716202-2d42-11e8-806f-942674f64fb0.png)

**Comment by gregallensworth** [comment]
I'll also be replacing the green SVG. The one that got into the repo is really big, and misshapen as well.

![image](https://user-images.githubusercontent.com/3117633/37792749-e1b463d4-2dc9-11e8-8fb1-42216480a2a5.png)

**Comment by danrademacher** [comment]
Interesting. I opened the existing orange one, changed color, and saved. So I assume the orange one is also very large and misshapen?

**Comment by gregallensworth** [comment]
All set.

![image](https://user-images.githubusercontent.com/3117633/37793096-e9df1760-2dca-11e8-941b-6f35074e0a9f.png)


* Markers are redrawn on details panel changes.
* Alternative icon used for the selected location.
* Bonus: Also adjusts the zindex of the marker so it shows over top of others.
* Double bonus: Details panel, now shows the marker if an event is All Day (lacks both a start and end time) per #33 .
