### ISSUE TITLE
"Show All Days" search option

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/DDH_HomelessServices#36]
People having trouble finding Dental and other scarce things. Request is "Show all Days"

Seems like it should be straight forward, but maybe some issues I'm not thinking of?

**Comment by gregallensworth** [comment]
I have added a new "Any Day" date option which sets the date to null, and made date specification optional.

![image](https://user-images.githubusercontent.com/3117633/37792314-b8347d42-2dc8-11e8-8351-6b40b147508b.png)

*This may not achieve what they want, however* as the issue of finding Dental and Women and so on isn't the day filtering, but that no places have been tagged with that service. If they could walk us through a more detailed scenario, that could be helpful in finding out whether we have solved a problem.
