### ISSUE TITLE
bouncing search items with GPS enabled

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/DDH_HomelessServices#37]
We have a bouncing search result (again?) when we're sorting by time.

Here's an animation:
http://recordit.co/NosfCyFlL4

But it stops if you select Sort by Distance.

**Comment by gregallensworth** [comment]
Hm, yes The sorting was known not to be "stable" -- that is, known *not* to guarantee that items keep the same position in the event of a tie.

This should be an easy fix by adding the ID as a tie-breaker. Two places with the same distance, same time, etc. would then be guaranteed for *this one* to come before *that one* so they would never "mysteriously" swap.

**Comment by gregallensworth** [comment]
The new sorting by time should be much improved, as well as stable.


In this process, the start-time/end-time sorting needed to be completely reworked, and this was opportune in light of the All Day decision made in #33 New behaviors should be just great.

**No ending time** still sorts by starting time.

<img width="561" alt="noendtime-stillsortsbystart" src="https://user-images.githubusercontent.com/3117633/37789916-6173c0b8-2dc2-11e8-83d6-be759216937d.png">


**No starting time** is sorted to the start of the list, on grounds that it has already started.

<img width="558" alt="nostart-first" src="https://user-images.githubusercontent.com/3117633/37789917-6189e816-2dc2-11e8-81e9-dae6e6c64d47.png">


**Ties for starting time** are sorted by ending time, so the more urgent event comes first.

<img width="566" alt="samestart-sortbyend" src="https://user-images.githubusercontent.com/3117633/37789918-61a34112-2dc2-11e8-9760-1a3a1b35f59c.png">
