### ISSUE TITLE
Add phone number to the details view on map

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/DDH_HomelessServices#38]
Added new `phone` field that's now populated by the shelter staff.

Just add above the Website/Facebook link:
![image](https://user-images.githubusercontent.com/1423200/37749251-5e366b04-2d44-11e8-9344-7ad17b8ddc71.png)

Since mobile is the target, maybe wrap in `tel:` and then it's a link on a phone? (I only somewhat understand how that work.

**Comment by gregallensworth** [comment]
Reopen: Some phone numbers have extra spaces in them, and this looks weird. See the extra space on this one.

![image](https://user-images.githubusercontent.com/3117633/37795556-0593d58e-2dd2-11e8-8eee-5866d8f7f05f.png)
